version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
